apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: drone
  source:
    repoURL: https://github.com/LinusThorsell/kubes.git
    targetRevision: main
    path: manifests/drone
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
